/home/wang9/anaconda3/envs/torch_1.11/lib/python3.10/site-packages/torch/utils/data/dataloader.py:563: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
0it [00:00, ?it/s]1it [00:45, 45.38s/it]2it [00:46, 19.19s/it]3it [00:46, 10.71s/it]4it [00:47,  6.72s/it]5it [00:48,  4.52s/it]6it [00:48,  3.19s/it]7it [00:49,  2.35s/it]8it [00:49,  1.79s/it]9it [00:50,  1.43s/it]10it [00:51,  1.18s/it]11it [00:51,  1.00s/it]12it [00:52,  1.13it/s]13it [00:52,  1.25it/s]14it [00:53,  1.34it/s]15it [00:54,  1.42it/s]16it [00:54,  1.48it/s]17it [01:24,  9.54s/it]18it [01:25,  6.86s/it]19it [01:26,  4.98s/it]20it [01:26,  3.67s/it]21it [01:27,  2.82s/it]22it [01:28,  2.16s/it]23it [01:28,  1.70s/it]24it [01:29,  1.37s/it]25it [01:30,  1.14s/it]26it [01:30,  1.02it/s]27it [01:36,  2.56s/it]28it [01:37,  1.98s/it]29it [01:38,  1.57s/it]30it [01:38,  1.28s/it]31it [01:39,  1.08s/it]32it [01:40,  1.06it/s]33it [02:04,  8.08s/it]34it [02:10,  7.27s/it]35it [02:10,  5.28s/it]36it [02:18,  5.94s/it]37it [02:18,  4.34s/it]38it [02:19,  3.22s/it]39it [02:20,  2.44s/it]40it [02:20,  1.89s/it]41it [02:21,  1.51s/it]42it [02:21,  1.24s/it]43it [02:27,  2.54s/it]44it [02:28,  1.96s/it]45it [02:28,  1.56s/it]46it [02:29,  1.27s/it]47it [02:29,  1.07s/it]48it [02:30,  1.07it/s]49it [02:40,  3.76s/it]50it [02:41,  2.82s/it]51it [02:42,  2.16s/it]52it [02:44,  2.10s/it]53it [02:44,  1.66s/it]54it [02:45,  1.34s/it]55it [02:45,  1.12s/it]56it [02:46,  1.03it/s]57it [02:47,  1.16it/s]58it [02:47,  1.27it/s]59it [02:48,  1.27it/s]60it [02:49,  1.36it/s]61it [02:49,  1.43it/s]61it [02:49,  2.79s/it]
Traceback (most recent call last):
  File "/usr/local/bin/jobinfo.py", line 14, in <module>
    gpu_stats = getstats(sys.argv[1])
  File "/usr/local/bin/jobinfo.py", line 10, in getstats
    with open(fname) as stats_file:
IOError: [Errno 2] No such file or directory: '/run/gpustats.json'
